document.write('<div class="knav-sidebar knav-animate-left" style="display:none" id="mySidebar">');
document.write('<div class="closebutton-container"><button class="knav-button" onclick="knav_close()"><span class="dot"><img src="../images/close-hamburger2.svg" width="60" height="60" /></span></button></div>');
document.write('<div class="dividers">');
document.write('<button class="accordion" id="advance-care-planning" onclick="myAccFunc(\'advance-care-planning\')">Advance Care Planning</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Donation of a body for Anatomical Examination" onClick="window.location = \'../advance-care-planning/donation-of-a-body-for-anatomical-examination.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Cornea donation" onClick="window.location = \'../advance-care-planning/cornea-donation.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Funeral directors" onClick="window.location = \'../advance-care-planning/funeral-directors.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Respect" onClick="window.location = \'../advance-care-planning/respect.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Public health funerals" onClick="window.location = \'../advance-care-planning/public-health-funerals.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="breathing" onclick="myAccFunc(\'breathing\')">Breathing</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="The respiratory system and breathlessness" onClick="window.location = \'../breathing/breathing-respiratory-system-breathlessness.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Oxygen therapy" onClick="window.location = \'../breathing/breathing-oxygen-therapy.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Emergency and ambulatory oxygen" onClick="window.location = \'../breathing/breathing-emergency-ambulatory-oxygen.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Ordering oxygen therapy supplies and concentrators" onClick="window.location = \'../breathing/breathing-ordering-oxygen-therapy-supplies-and-concentrators.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Tracheostomy and laryngectomy care" onClick="window.location = \'../breathing/breathing-tracheostomy-and-laryngectomy-care.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Suction" onClick="window.location = \'../breathing/breathing-suction.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="clinic-room" onclick="myAccFunc(\'clinic-room\')">Clinic Room</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Approved abbreviations" onClick="window.location = \'../clinic-room/clinic-room-abbreviations.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Drug conversions" onClick="window.location = \'../clinic-room/clinic-room-drug-conversions.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Subcutaneous drug compatibility" onClick="window.location = \'../clinic-room/clinic-room-subcutaneous-drug-compatibility.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Controlled drugs stock" onClick="window.location = \'../clinic-room/clinic-room-stock-controlled-drugs.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Drugs stock" onClick="window.location = \'../clinic-room/clinic-room-stock-drugs.aspx\'">');
document.write('<input type="button" class="panelbutton" value="IV Guidelines" onClick="window.location = \'../clinic-room/clinic-room-iv-guidelines.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Incident pain and Abstral®" onClick="window.location = \'../clinic-room/clinic-room-abstral.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Lab results" onClick="window.location = \'../clinic-room/clinic-room-lab-results.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Opioid medication principles in palliative care" onClick="window.location = \'../clinic-room/clinic-room-opioid-medication-principles.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Syringe Drivers" onClick="window.location = \'../clinic-room/clinic-room-syringe-drivers.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="diabetes-care" onclick="myAccFunc(\'diabetes-care\')">Diabetes Care</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="About diabetes" onClick="window.location = \'../diabetes-care/diabetes-care-about-diabetes.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Diabetes management in palliative care" onClick="window.location = \'../diabetes-care/diabetes-diabetes-management-in-palliative-care.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Diabetic emergencies" onClick="window.location = \'../diabetes-care/diabetes-diabetic-emergencies.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Prescribing and management guidelines for doctors" onClick="window.location = \'../diabetes-care/diabetes-doctors.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="discharge" onclick="myAccFunc(\'discharge\')">Discharge</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="The Discharge Pathway Planning Process" onClick="window.location = \'../discharge/discharge-discharge-pathway.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Discharge checklist for IPU nurses" onClick="window.location = \'../discharge/discharge-discharge-checklist.aspx\'">');
document.write('<input type="button" class="panelbutton" value="TTO medication" onClick="window.location = \'../discharge/discharge-tto-medication.aspx\'">');
//document.write('<input type="button" class="panelbutton" value="Nursing handover letter" onClick="window.location = \'../discharge/discharge-nursing-handover-letter.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="enteral-feeding" onclick="myAccFunc(\'enteral-feeding\')">Enteral Feeding</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Background knowledge" onClick="window.location = \'../enteral-feeding/enteral-feeding-background-knowledge.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Care of PEG tubes" onClick="window.location = \'../enteral-feeding/enteral-feeding-care-of-peg-tube.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Care of RIG tubes" onClick="window.location = \'../enteral-feeding/enteral-feeding-care-of-rig-tube.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Feed and medication administration" onClick="window.location = \'../enteral-feeding/enteral-feeding-feed-and-medication-administration.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Complications" onClick="window.location = \'../enteral-feeding/enteral-feeding-complications.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="infection-control" onclick="myAccFunc(\'infection-control\')">Infection Control (IPC)</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="ANTT" onClick="window.location = \'../infection-control/infection-control-antt.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Cleaning duties" onClick="window.location = \'../infection-control/infection-control-cleaning-duties.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Handwashing" onClick="window.location = \'../infection-control/infection-control-handwashing.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Infectious diseases" onClick="window.location = \'../infection-control/infection-control-infectious-diseases.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Infections and illness in staff" onClick="window.location = \'../infection-control/infection-control-infections-illness-staff.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Isolation and outbreak management" onClick="window.location = \'../infection-control/infection-control-isolation-and-outbreak.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Linen and bed making" onClick="window.location = \'../infection-control/infection-control-linen-and-bedmaking.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Personal protective equipment (PPE)" onClick="window.location = \'../infection-control/infection-control-ppe.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Sharps" onClick="window.location = \'../infection-control/infection-control-sharps.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Specimens and samples" onClick="window.location = \'../infection-control/infection-control-specimens-and-samples.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Spillages" onClick="window.location = \'../infection-control/infection-control-spillages.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Uniforms" onClick="window.location = \'../infection-control/infection-control-uniform.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Waste management" onClick="window.location = \'../infection-control/infection-control-waste-management.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="palliative-care-emergencies" onclick="myAccFunc(\'palliative-care-emergencies\')">Palliative care emergencies</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Haemorrhage" onClick="window.location = \'../palliative-care-emergencies/palliative-care-emergencies-haemorrhage.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Malignant hypercalcaemia" onClick="window.location = \'../palliative-care-emergencies/palliative-care-emergencies-malignant-hypercalcaemia.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Malignant spinal cord compression (MSCC)" onClick="window.location = \'../palliative-care-emergencies/palliative-care-emergencies-mscc.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Neutropenic sepsis" onClick="window.location = \'../palliative-care-emergencies/palliative-care-emergencies-neutropenic-sepsis.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Seizures" onClick="window.location = \'../palliative-care-emergencies/palliative-care-emergencies-seizures.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Superior vena cava (SVC) obstruction" onClick="window.location = \'../palliative-care-emergencies/palliative-care-emergencies-svco.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="palliative-care-outcome-measures" onclick="myAccFunc(\'palliative-care-outcome-measures\')">Palliative care outcome measures</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Palliative care outcome measures" onClick="window.location = \'../palliative-care-outcome-measures/palliative-outcome-measures.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="print-catalogue" onclick="myAccFunc(\'print-catalogue\')">Print Catalogue</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Charts and documentation" onClick="window.location = \'../print-catalogue/print-catalogue-charts-and-documentation.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Posters, leaflets and booklets" onClick="window.location = \'../print-catalogue/print-catalogue-posters-leaflets-and-booklets.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Referral forms and guidance" onClick="window.location = \'../print-catalogue/print-catalogue-referral-forms-and-guidance.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="psychosocial-and-welfare" onclick="myAccFunc(\'psychosocial-and-welfare\')">Psychosocial and Welfare</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="DoLS" onClick="window.location = \'../psychosocial-and-welfare/dols.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Homelessness" onClick="window.location = \'../psychosocial-and-welfare/homelessness.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Public health funerals" onClick="window.location = \'../psychosocial-and-welfare/public-health-funerals.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Safeguarding adults" onClick="window.location = \'../psychosocial-and-welfare/safeguarding-adults.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Child protection and safeguarding" onClick="window.location = \'../psychosocial-and-welfare/child-protection-safeguarding.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="research" onclick="myAccFunc(\'research\')">Research</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Journal Articles" onClick="window.location = \'../research/journal-articles.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="skin-integrity-and-personal-care" onclick="myAccFunc(\'skin-integrity-and-personal-care\')">Skin Integrity and Personal Care</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Skin anatomy and functions" onClick="window.location = \'../skin-integrity-and-personal-care/skin-integrity-and-personal-care-skin-anatomy-and-functions.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Risk assessment and prevention measures" onClick="window.location = \'../skin-integrity-and-personal-care/skin-integrity-and-personal-care-risk-assessment-and-preventionx.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Pressure injury grading and wound evaluation" onClick="window.location = \'../skin-integrity-and-personal-care/skin-integrity-and-personal-care-pressure-injury-grading-and-evaluation.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Pressure injury and wound care" onClick="window.location = \'../skin-integrity-and-personal-care/skin-integrity-and-personal-care-pressure-injury-and-wound-care.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Products we currently use" onClick="window.location = \'../skin-integrity-and-personal-care/skin-integrity-and-personal-care-products-we-currently-use.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Mouthcare" onClick="window.location = \'../skin-integrity-and-personal-care/skin-integrity-and-personal-care-skin-mouth-care.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Tissue viability nurse (TVN) referral" onClick="window.location = \'../skin-integrity-and-personal-care/skin-integrity-and-personal-care-tissue-viability-nurse-referral.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="spirituality-and-beliefs" onclick="myAccFunc(\'spirituality-and-beliefs\')">Spirituality and Beliefs</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Buddhism" onClick="window.location = \'../spirituality-and-beliefs/buddhism.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Christianity" onClick="window.location = \'../spirituality-and-beliefs/christianity.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Judaism" onClick="window.location = \'../spirituality-and-beliefs/judaism.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Chaplaincy Contacts" onClick="window.location = \'../spirituality-and-beliefs/chaplaincy-contacts.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Religious and National Days of Awareness" onClick="window.location = \'../spirituality-and-beliefs/religious-and-national-days.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="symptom-control" onclick="myAccFunc(\'symptom-control\')">Symptom Control</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Nausea and Vomiting" onClick="window.location = \'../symptom-control/symptom-control-nausea-vomiting.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Pain" onClick="window.location = \'../symptom-control/symptom-control-pain.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('<button class="accordion" id="the-hub" onclick="myAccFunc(\'the-hub\')">The Hub (OOH)</button>');
document.write('<div class="panel">');
document.write('<input type="button" class="panelbutton" value="Answering a call" onClick="window.location = \'../the-hub/the-hub-answering-a-call.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Monday to Friday contact numbers" onClick="window.location = \'../the-hub/the-hub-monday-friday.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Weekend and bank holiday contact numbers" onClick="window.location = \'../the-hub/the-hub-weekends.aspx\'">');
//document.write('<input type="button" class="panelbutton" value="Night sitters" onClick="window.location = \'../the-hub/the-hub-night-sitters.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Pharmacy contacts" onClick="window.location = \'../the-hub/the-hub-pharmacies.aspx\'">');
document.write('<input type="button" class="panelbutton" value="Useful information" onClick="window.location = \'../the-hub/the-hub-useful-information.aspx\'">');
document.write('</div> <!-- close panel -->');
document.write('</div> <!-- close dividers -->');
document.write('</div> <!-- close mySidebar -->');
